### PR TITLE
fixes #114, #

### LINKED ISSUE #114: Add "Status" attribute to equations
We will need a Status to track if an equation is available in Test, Production, or if it's been superseded.

### LINKED ISSUE #116: Return Regression Region 'description' with Scenarios
The "Description" that is associated with a Regression Region is not returned with Scenarios.

### PR DESCRIPTION
**Pull request by kjacobsen16**
- fixes #114 - fully incorporate status ID, add "DateStatusModified" property to regression regions table
- scenarios now filtered by status ID depending on environment and "x-is-streamstats" header (ss clients will need to send this header along with a value of "true"
- added status controller, endpoints and documentation
- also fixes #116 (reg region description now sent to scenarios)

### CODE REVIEW

File: NSSAgent/NSSAgent.cs [hunk 1]
```diff
@@ -515,17 +520,54 @@ public IQueryable<String> GetRoles()
...
+        public IQueryable<Status> GetApplicableStatuses(Manager manager = null, bool isStreamStats = false)
+        {
+            var query = this.Select<Status>();
+            var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
+
+            // set applicable statuses for each environment
+            var SSProdStatuses = new List<string> { "SS Approved" };
+            var SSStagingStatuses = new List<string> { "SS Approved", "Review" };
+            var NSSStagingStatuses = new List<string> { "Review", "Approved", "SS Approved" };
+            var NSSProdStatuses = new List<string> { "Approved", "SS Approved" };
```
Comment (kjacobsen16) [inline NSSAgent/NSSAgent.cs:543]: This could probably be done better, I tried to add it to the appsettings.json and had trouble. If there's a good way to do this, let me know.

File: FU_NSSDB/NSSdbOps.cs [hunk 2]
```diff
@@ -238,7 +238,7 @@ private string getMySqlSql(SQLType type)
                     results = @"INSERT INTO ""nss"".""Regions""(""Name"",""Code"") VALUES('{0}','{1}')";
                     break;
                 case SQLType.e_regressionregion:
-                    results = @"INSERT INTO ""nss"".""RegressionRegions""(""Name"",""Code"",""Description"",""CitationID"") VALUES('{0}', '{1}', '{2}',{3})";
+                    results = @"INSERT INTO ""nss"".""RegressionRegions""(""Name"",""Code"",""Description"",""CitationID"",""StatusID"") VALUES('{0}', '{1}', '{2}',{3}, 4)";
```
Comment (jknewson) [inline FU_NSSDB/NSSdbOps.cs:241]: is 4 suppose to be the statusID? or will this be passed in as an argument? The way it is written 4 will be the statusID for all regressionRegions by default. It'll probably be easier to maintain long term to pass the argument [here ](https://github.com/USGS-WiM/NSSServices/blob/KJ-114/FU_NSSDB/ForceUpdate.cs#L221)in as a value rather than setting the default in the sql. (just a suggestion, not necessary)

File: NSSAgent/NSSAgent.cs [hunk 3]
```diff
@@ -100,10 +100,15 @@ public interface INSSAgent:IAuthenticationAgent
...
+
+        //Statuses
+        IQueryable<Status> GetStatuses();
+        Task<Status> GetStatus(Int32 ID);
+        IQueryable<Status> GetApplicableStatuses(Manager manager = null, bool isStreamStats = false);
+
         //Scenarios
         //IQueryable<Scenario> GetScenarios(List<string> regionList, List<string> regressionRegionList, List<string> statisticgroupList = null, List<string> regressionTypeIDList = null, List<string> extensionMethodList = null, Int32 systemtypeID = 0);
-        IQueryable<Scenario> GetScenarios(List<string> regionList=null, Geometry geom=null, List<string> regressionRegionList = null, List<string> statisticgroupList = null, List<string> regressionTypeIDList = null, List<string> extensionMethodList = null, Int32 systemtypeID = 0, Manager manager = null);
+        IQueryable<Scenario> GetScenarios(List<string> regionList=null, Geometry geom=null, List<string> regressionRegionList = null, List<string> statisticgroupList = null, List<string> regressionTypeIDList = null, List<string> extensionMethodList = null, Int32 systemtypeID = 0, Manager manager = null, bool isStreamStats = false);
```
Comment (jknewson) [inline NSSAgent/NSSAgent.cs:111]: hmm, yeah I'm still not sold on the idea of having a streamstats 'flag' for configuration. I think a policy type of approach might be more sustainable long term.

File: NSSServices/Controllers/ScenariosController.cs [hunk 4]
```diff
@@ -203,16 +203,19 @@ public async Task<IActionResult> Delete([FromQuery] Int32 regressionregionID, [F
...
                 extensionList = parse(extensions);
+                var isStreamStats = false;
+                // check for SS header
+                if (Request.Headers.FirstOrDefault(h => h.Key.ToUpper() == "X-IS-STREAMSTATS").Value.FirstOrDefault() == "true") isStreamStats = true;
 
                 if (geom != null)
                 {
                     if (!agent.allowableGeometries.Contains(geom.GeometryType)) throw new BadRequestException("Geometry is not of type: " + String.Join(',', agent.allowableGeometries));
-                    entities = agent.GetScenarios(RegionList, geom, null, statisticgroupList, regressiontypeList, extensionList, unitsystem, LoggedInUser()).ToList();
+                    entities = agent.GetScenarios(RegionList, geom, null, statisticgroupList, regressiontypeList, extensionList, unitsystem, LoggedInUser(), isStreamStats).ToList();
```
Comment (jknewson) [inline NSSServices/Controllers/ScenariosController.cs:213]: same as previous comment regarding tightly coupling client/service.

File: NSSServices/Controllers/StatusesController.cs [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+using NSSAgent;
+using System.Threading.Tasks;
+using System.Collections.Generic;
+using WIM.Services.Attributes;
+
+namespace NSSServices.Controllers
+{
+    [Route("[controller]")]
+    [APIDescription(type = DescriptionType.e_link, Description = "/Docs/Statuses/summary.md")]
+    public class StatusesController : NSSControllerBase
```
Comment (jknewson) [inline NSSServices/Controllers/StatusesController.cs:33]: 'status' (plural context) is more common than using the anglicized 'statuses'

File: FU_NSSDB/NSSdbOps.cs (hunk 2 above)
Comment (kjacobsen16) [reply FU_NSSDB/NSSdbOps.cs:241]: Yeah this is correct, Pete wants all regression regions coming from SSDB to be set to the statusID of "4" (SS approved) by default, but if I'm going in update things anyway, I might move it to the location you linked.

File: NSSAgent/NSSAgent.cs (hunk 3 above)
Comment (kjacobsen16) [reply NSSAgent/NSSAgent.cs:111]: How would you recommend doing this? Right now, it's expecting a header "X-Is-Streamstats" sent through by the client.

File: NSSServices/Controllers/StatusesController.cs (hunk 5 above)
Comment (kjacobsen16) [reply NSSServices/Controllers/StatusesController.cs:33]: How did I not know "status" is plural? 😆 thank you!

File: NSSAgent/NSSAgent.cs (hunk 3 above)
Comment (jknewson) [reply NSSAgent/NSSAgent.cs:111]: hmm, thats odd the rest of my comment didn't stay. I can't remember exactly what I wrote last time, but the thought would be to move most of the Streamstats  'configuration' stuff out of the agent and into the services. This would allow the agent to be more flexible and allow the services to provide the configuration. A lot of the configuration could be performed in a custom middleware pipeline method that could capture the client info and write the policy claim, similar to how we are doing roles, but this one could be specific to nssservices. Regarding  the [filtering](https://github.com/USGS-WiM/NSSServices/blob/KJ-114/NSSAgent/NSSAgent.cs#L561) instead of 'isStreamstats' supply a List of status, similar to how we are filtering the regions, regressionregions etc.... leaving the method more flexible, and not tied to a client variable....
Hopefully that makes sense

File: NSSServices/Controllers/StatusesController.cs (hunk 5 above)
Comment (jknewson) [reply NSSServices/Controllers/StatusesController.cs:33]: well statuses is valid, but just not as common 
[Here ](https://en.wikipedia.org/wiki/Talk%3AStatus#Plural_of_status)is an interesting writeup about it

**Comment by kjacobsen16** [comment]
@jknewson I'm not sure if this is what you meant, but I moved the `applicableStatus` function out of the agent to the controller base. If there's still a better way, we can add that as an enhancement. Thanks!
